openapi: 3.2.0
info:
  version: v1
  title: DCX GBC API V2 Retail Customer API
  description: 'The Green Button Connect API provides an access to RESTful services provided by ConEdison and Third Party Applications. These APIs allow application developers full access, in Green Button Format, to Energy Usage Information for the purpose of developing new Green Button Applications.Access to Green Button APIs requires an OAuth2 Access Token. Insert Access Tokens in the field labelled ''Access Token: '' at the top of the page prior to selecting the ''Try It Out!'' button:'
servers:
- url: https://provided-by-coned/gbc/espi/1_1
tags:
- name: RetailCustomer
paths:
  /resource/Customer/{subscriptionId}:
    get:
      tags:
      - RetailCustomer
      operationId: getCustomerInformationBySubscription
      parameters:
      - name: subscriptionId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: BadRequest
        '401':
          description: Unauthorized
      servers:
      - url: https://provided-by-coned/gbc/espi/1_1
      summary: Get customer information by subscription
      x-summary-source: derived
  /resource/Customer/{subscriptionId}/CustomerAccount:
    get:
      tags:
      - RetailCustomer
      operationId: getCustomerAccountInSubscription
      parameters:
      - name: subscriptionId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: BadRequest
        '401':
          description: Unauthorized
      servers:
      - url: https://provided-by-coned/gbc/espi/1_1
      summary: Get customer account in subscription
      x-summary-source: derived
  /resource/Customer/{subscriptionId}/CustomerAccount/{accountId}:
    get:
      tags:
      - RetailCustomer
      operationId: getCustomerAccountByAccountIdInSubscription
      parameters:
      - name: subscriptionId
        in: path
        required: true
        schema:
          type: string
      - name: accountId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: BadRequest
        '401':
          description: Unauthorized
      servers:
      - url: https://provided-by-coned/gbc/espi/1_1
      summary: Get customer account by account id in subscription
      x-summary-source: derived
  /resource/Customer/{subscriptionId}/CustomerAccount/{accountId}/CustomerAgreement:
    get:
      tags:
      - RetailCustomer
      operationId: getCustomerAgreementByAccountIdInSubscription
      parameters:
      - name: subscriptionId
        in: path
        required: true
        schema:
          type: string
      - name: accountId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: BadRequest
        '401':
          description: Unauthorized
      servers:
      - url: https://provided-by-coned/gbc/espi/1_1
      summary: Get customer agreement by account id in subscription
      x-summary-source: derived
  /resource/Customer/{subscriptionId}/CustomerAccount/{accountId}/CustomerAgreement/{customerAgreementId}:
    get:
      tags:
      - RetailCustomer
      operationId: getCustomerAgreementByCustomerAgreementId
      parameters:
      - name: subscriptionId
        in: path
        required: true
        schema:
          type: string
      - name: accountId
        in: path
        required: true
        schema:
          type: string
      - name: customerAgreementId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: BadRequest
        '401':
          description: Unauthorized
      servers:
      - url: https://provided-by-coned/gbc/espi/1_1
      summary: Get customer agreement by customer agreement id
      x-summary-source: derived
  /resource/Customer/{subscriptionId}/CustomerAccount/{accountId}/CustomerAgreement/{customerAgreementId}/ServiceLocation:
    get:
      tags:
      - RetailCustomer
      operationId: getAllServiceLocationByCustomerAgreementIdAndAccountIdInSubscription
      parameters:
      - name: subscriptionId
        in: path
        required: true
        schema:
          type: string
      - name: accountId
        in: path
        required: true
        schema:
          type: string
      - name: customerAgreementId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: BadRequest
        '401':
          description: Unauthorized
      servers:
      - url: https://provided-by-coned/gbc/espi/1_1
      summary: Get all service location by customer agreement id and account id in subscription
      x-summary-source: derived
  ? /resource/Customer/{subscriptionId}/CustomerAccount/{accountId}/CustomerAgreement/{customerAgreementId}/ServiceLocation/{serviceLocationId}
  : get:
      tags:
      - RetailCustomer
      operationId: getServiceLocationByServiceLocationId
      parameters:
      - name: subscriptionId
        in: path
        required: true
        schema:
          type: string
      - name: accountId
        in: path
        required: true
        schema:
          type: string
      - name: customerAgreementId
        in: path
        required: true
        schema:
          type: string
      - name: serviceLocationId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: BadRequest
        '401':
          description: Unauthorized
      servers:
      - url: https://provided-by-coned/gbc/espi/1_1
      summary: Get service location by service location id
      x-summary-source: derived
  ? /resource/Customer/{subscriptionId}/CustomerAccount/{accountId}/CustomerAgreement/{customerAgreementId}/ServiceLocation/{serviceLocationId}/Meter
  : get:
      tags:
      - RetailCustomer
      operationId: getAllMetersForServiceLocationInSubscription
      parameters:
      - name: subscriptionId
        in: path
        required: true
        schema:
          type: string
      - name: accountId
        in: path
        required: true
        schema:
          type: string
      - name: customerAgreementId
        in: path
        required: true
        schema:
          type: string
      - name: serviceLocationId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: BadRequest
        '401':
          description: Unauthorized
      servers:
      - url: https://provided-by-coned/gbc/espi/1_1
      summary: Get all meters for service location in subscription
      x-summary-source: derived
  ? /resource/Customer/{subscriptionId}/CustomerAccount/{accountId}/CustomerAgreement/{customerAgreementId}/ServiceLocation/{serviceLocationId}/Meter/{serialNumber}
  : get:
      tags:
      - RetailCustomer
      operationId: getMeterBySerialNumberId
      parameters:
      - name: subscriptionId
        in: path
        required: true
        schema:
          type: string
      - name: accountId
        in: path
        required: true
        schema:
          type: string
      - name: customerAgreementId
        in: path
        required: true
        schema:
          type: string
      - name: serviceLocationId
        in: path
        required: true
        schema:
          type: string
      - name: serialNumber
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: BadRequest
        '401':
          description: Unauthorized
      servers:
      - url: https://provided-by-coned/gbc/espi/1_1
      summary: Get meter by serial number id
      x-summary-source: derived
